<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Oceanpayment
 * @package 	Oceanpayment_Qiwi
 */
?>

<div class="form-divst">
	<img style="height:40px" src="<?php echo $this->getSkinUrl('images/op_qiwi/op_qiwi.png') ?>" />
</div>
<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display: none;" >
	  <li>
        <label for="pay_countryCode" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
      	<div class="input-box">
           <select name="payment[pay_countryCode]" id="pay_countryCode" >
                 <option value="+7"><?php echo $this->__('Russian Federation(+7)') ?></option>
                 <option value="+77"><?php echo $this->__('Kazakhstan(+77)') ?></option>
                 <option value="+380"><?php echo $this->__('Ukraine(+380)') ?></option>              				 
				 <option value="+373"><?php echo $this->__('The Republic of Moldova(+373)') ?></option>
                 <option value="+374"><?php echo $this->__('Armenia(+374)') ?></option>
                 <option value="+372"><?php echo $this->__('Estonia(+372)') ?></option>
                 <option value="+994"><?php echo $this->__('Azerbaijan(+994)') ?></option>
                 <option value="+82"><?php echo $this->__('South Korea(+82)') ?></option>
				 <option value="+507"><?php echo $this->__('Panama(+507)') ?></option>
                 <option value="+371"><?php echo $this->__('Latvia(+371)') ?></option>
                 <option value="+370"><?php echo $this->__('Lithuania(+370)') ?></option>
                 <option value="+996"><?php echo $this->__('Kyrgyzstan(+996)') ?></option>
                 <option value="+9995"><?php echo $this->__('Georgia(+9995)') ?></option>
				 <option value="+992"><?php echo $this->__('Tajikistan(+992)') ?></option>
                 <option value="+44"><?php echo $this->__('United Kingdom(+44)') ?></option>				 
				 <option value="+998"><?php echo $this->__('Uzbekistan(+998)') ?></option>
                 <option value="+972"><?php echo $this->__('Israel(+972)') ?></option>
                 <option value="+66"><?php echo $this->__('Thailand(+66)') ?></option>
                 <option value="+90"><?php echo $this->__('South Turkey(+90)') ?></option>
                 <option value="+91"><?php echo $this->__('India(+91)') ?></option>               
           </select>
      	</div>
      </li> 
      <li>
        <label for="pay_userName" class="required"><em>*</em><?php echo $this->__('Enter your phone') ?></label>
      	<div class="input-box">
           <input id="pay_userName" name="payment[pay_userName]" class="input-text required-entry  validate-number validate-length minimum-length-6  maximum-length-12"   type="text" maxlength="12">
      	</div>
      </li> 
</ul>