<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Oceanpayment
 * @package 	Oceanpayment_POLi
 * @copyright	Copyright (c) 2009 Oceanpayment,LLC. (http://www.oceanpayment.com)
 */
?>

<div class="form-divst">
	<img style="height:40px" src="<?php echo $this->getSkinUrl('images/op_poli/op_poli.png') ?>" />
</div>
<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display: none;" >
      <li>
      		<label for="pay_countryCode" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
	      	<div class="input-box">
	           <select name="pay_countryCode" id="pay_countryCode" class="validate-select" >
	           		<option value=""><?php echo $this->__('- Select -') ?></option>
	           		<?php foreach ($this->getCountry() as $CountryCode){?>
	           			<option value="<?php echo $CountryCode;?>"><?php echo $this->getCountryText($CountryCode); ?></option>
	           		<?php }?>
	           </select>
	      	</div>
      </li>
</ul>