<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category	Oceanpayment
 * @package 	Oceanpayment_BROnlineBank
 */
?>

<div class="form-divst">
	<img style="height:40px" src="<?php echo $this->getSkinUrl('images/op_bronlinebank/op_bronlinebank.png') ?>" />
</div>
<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display: none;" >
	  <li>
        <label for="pay_bankCode" class="required"><em>*</em><?php echo $this->__('Bank') ?></label>
      	<div class="input-box">
           <select name="pay_bankCode" id="pay_bankCode" >
                 <option value="I"><?php echo $this->__('Itau') ?></option>
                 <option value="BB"><?php echo $this->__('Banco do Brasil') ?></option>
                 <option value="B"><?php echo $this->__('Bradesco') ?></option>
                 <option value="SB"><?php echo $this->__('Santander') ?></option>             
           </select>
      	</div>
      </li> 
      <li>
        <label for="pay_cpf" class="required"><em>*</em><?php echo $this->__('Enter your CPF/CNPJ') ?></label>
      	<div class="input-box">
           <input type="text" id="pay_cpf" name="pay_cpf" placeholder="CFP / CNPJ" maxlength="14" class="required-entry validate-number validate-length minimum-length-11 maximum-length-14" onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')" />
      	</div>
      </li> 
</ul>